// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220710113146_EditAncIngredient")]
    partial class EditAncIngredient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.AncIngredient", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AncId")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .HasColumnType("longtext");

                    b.HasKey("Name");

                    b.ToTable("AncIngredients");
                });

            modelBuilder.Entity("Domain.ItemAncClassifier", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("AncIngredientId")
                        .HasColumnType("int");

                    b.Property<string>("AncIngredientName")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Coefficient")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Name");

                    b.HasIndex("AncIngredientName");

                    b.ToTable("ItemAncRelations");
                });

            modelBuilder.Entity("Domain.ItemAncClassifier", b =>
                {
                    b.HasOne("Domain.AncIngredient", "AncIngredient")
                        .WithMany()
                        .HasForeignKey("AncIngredientName");

                    b.Navigation("AncIngredient");
                });
#pragma warning restore 612, 618
        }
    }
}
